all:
	gcc -std=gnu99 -c main.c
	gcc -std=gnu99 -c admin.c
	gcc -std=gnu99 -c menuc.c
	gcc -std=gnu99 -c tool.c
	gcc -std=gnu99 -c supermanager.c
	gcc -std=gnu99 -c manager.c
	gcc -std=gnu99 -c teacher.c
	gcc -std=gnu99 -c student.c
	gcc -std=gnu99 -c teacher_info.c
	gcc -std=gnu99 -c teacher_score.c
	gcc main.o admin.o menuc.o tool.o supermanager.o manager.o teacher.o student.o teacher_info.o teacher_score.o -o Stu
