all:
	gcc -std=gnu99 -c main.c 
	gcc -std=gnu99 -c listofstu.c
	gcc -std=gnu99 -c show.c
	gcc -std=gnu99 -c teacher.c
	gcc -std=gnu99 -c admini.c
	gcc -std=gnu99 -c common.c
	gcc -std=gnu99 -c wr.c
	gcc main.o listofstu.o show.o teacher.o admini.o common.o wr.o -o student
